Name:           ros-indigo-pluginlib
Version:        1.10.0
Release:        3%{?dist}
Summary:        ROS pluginlib package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/pluginlib
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-indigo-class-loader
Requires:       ros-indigo-rosconsole
Requires:       ros-indigo-roslib >= 1.11.1
Requires:       tinyxml-devel
BuildRequires:  boost-devel
BuildRequires:  ros-indigo-catkin >= 0.5.68
BuildRequires:  ros-indigo-class-loader
BuildRequires:  ros-indigo-cmake-modules
BuildRequires:  ros-indigo-rosconsole
BuildRequires:  ros-indigo-roslib >= 1.11.1
BuildRequires:  tinyxml-devel

%description
The pluginlib package provides tools for writing and dynamically loading plugins
using the ROS build infrastructure. To work, these tools require plugin
providers to register their plugins in the package.xml of their package.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Dec 21 2014 Esteve Fernandez <esteve@osrfoundation.org> - 1.10.0-3
- Autogenerated by Bloom

